# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  release:
    types: [ "published" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Cleanup
  cleanup_project:
    uses: iovorobiev-games/unity_project_template/.github/workflows/cleanup.yml@main
  
  # This workflow contains a single job called "build"
  checkout:
    name: Checkout project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: cleanup_project

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

  build:
    uses: ./.github/workflows/build_action.yml
    needs: checkout
  
  deploy:
    name: Deploy project
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Zip release build
      - name: Zip
        run: sudo zip -r build/html.zip  build/WebGL

      - name: Upload to itch
        uses: Ayowel/butler-to-itch@v1
        with:
          butler_key: ${{ secrets.BUTLER_CREDENTIALS }}
          itch_user: ${{ vars.ITCH_USER }}
          itch_game: ${{ vars.ITCH_GAME }}
          version: ${{ github.ref_name }}
          files: |
                   build/html.zip
